spring:
  application:
    name: itoken-zipkin
  zipkin:
    base-url: http://192.168.242.132:9411
  boot:
    admin:
      client:
        url: http://192.168.242.132:8084

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.242.132:8761/eureka/,http://192.168.242.132:8861/eureka/,http://192.168.242.132:8961/eureka/

management:
  metrics:
    web:
      server:
        auto-time-requests: false