spring:
  zipkin:
    base-url: http://192.168.242.128:9411
  boot:
    admin:
      client:
        url: http://192.168.242.132:8084

mybatis:
  type-aliases-package: com.itoken.common.domain
  mapper-locations: classpath:mapper/*.xml

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.242.132:8761/eureka/,http://192.168.242.132:8861/eureka/,http://192.168.242.132:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info